# Generated by Django 5.0.9 on 2024-11-08 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_tema_recor'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='docente',
            name='asignatura',
            field=models.ForeignKey(default=1, help_text='Asignaturas que dicta', on_delete=django.db.models.deletion.CASCADE, to='cursos.asignatura'),
            preserve_default=False,
        ),
    ]
