# Generated by Django 5.0.9 on 2024-11-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_docente_asignatura_docente_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cactusCoins',
            field=models.IntegerField(default=0, editable=False, help_text='Puntos cactus del estudiante'),
        ),
    ]
