# Generated by Django 5.0.9 on 2024-11-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='recor',
        ),
    ]
