# Generated by Django 5.0.9 on 2024-11-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_tema_recor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='descripcion',
            field=models.TextField(help_text='Descripción de la asignatura', max_length=1500),
        ),
    ]
