# Generated by Django 5.1.2 on 2024-11-02 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Foro',
                'verbose_name_plural': 'Foros',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_id', models.PositiveIntegerField()),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor_tipo', models.ForeignKey(limit_choices_to={'model__in': ('estudiante', 'docente', 'tutor')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='discusiones.foro')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
    ]
